/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ahmed
 */
import java.awt.event.ActionListener;
import javax.swing.JTextField;
import javax.swing.Timer;

class Customer extends javax.swing.JFrame{
    private double  Balance;    

    public void setBalance(double Balance) {
        this.Balance = Balance;
    }

    public double getBalance() {
        return Balance;
    }
}
class Deposit extends Customer{
    private double CheckDeposit, CashDeposit;
    public Deposit() {
        this.CheckDeposit = 0.0;
        this.CashDeposit = 0.0;
    }

    public void setCheckDeposit(double CheckDeposit) {
        this.CheckDeposit = CheckDeposit;
        double Bal = getBalance();
        Bal = Bal + CheckDeposit;
        setBalance(Bal);
    }

    public void setCashDeposit(double CashDeposit) {
        this.CashDeposit = CashDeposit;
        double Bal = getBalance();
        Bal = Bal + CashDeposit;
        setBalance(Bal);
    }

    public double getCheckDeposit() {
        return CheckDeposit;
    }

    public double getCashDeposit() {
        return CashDeposit;
    }
    
}
class Withdraw extends Deposit{
    private String str;
    private double Withdraw,Bal;

    public void setWithdraw(double Withdraw) {
        this.Withdraw = Withdraw;
    }

    public void setBal(double Bal) {
        this.Bal = Bal;
    }

    public double getWithdraw() {
        return Withdraw;
    }

    public double getBal() {
        return Bal;
    }
    Withdraw(){
        str = "";
        Withdraw = 0.0;
        Bal = 0.0;
    }
    void ATMWithdraw(double Withdraw){
        this.Withdraw = Withdraw;
        Bal = getBalance();
        if (isMultipleof500(Withdraw) == false)
            str= "Wrong Input. Please Try Again";
        else{
            if(Bal == 0){
            str = "Your Account is zero.. Please Deposit";
            }
            else if(Withdraw > Bal){
            str = "Your Withdraw is Bigger than your Balance. Please Deposit";
            }
            else if(Bal > Withdraw){
            Bal = Bal - Withdraw;
            setBalance(Bal);
            str = "WithDraw Success Amount Withdrawn is: "+Withdraw;
            }
        }
    }
    static boolean isMultipleof500 (double n)
{
    while ( n > 0 )
        n = n - 500;
 
    if ( n == 0 )
        return true;
 
    return false;
}
        public String getStr(){
            return str;
        }
        public void setStr(String str){
            this.str=str;
        }
}

public class ATM extends Withdraw{

    private String str;
    
    /**
     * Creates new form ATM
     */
    public ATM() {
        //this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SubmitDeposit = new javax.swing.JButton();
        SubmitWithdraw = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Withdraw = new javax.swing.JTextField();
        Withdrawlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dep = new javax.swing.JLabel();
        CashDeposit = new javax.swing.JTextField();
        CheckDeposit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dep1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        WithdrawStatus = new javax.swing.JLabel();
        DepositStatus = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        SubmitDeposit.setText("Submit Deposit");
        SubmitDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDepositActionPerformed(evt);
            }
        });

        SubmitWithdraw.setText("Submit Withdraw");
        SubmitWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitWithdrawActionPerformed(evt);
            }
        });

        jLabel6.setText("For Withdraw:");

        Withdraw.setText(" ");
        Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawActionPerformed(evt);
            }
        });

        Withdrawlbl.setText("How Much do you want to withdraw?");

        jLabel1.setText("For Cash Deposit");

        dep.setText("How Much Cash do you want to Deposit?");

        CashDeposit.setText(" ");
        CashDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashDepositActionPerformed(evt);
            }
        });

        CheckDeposit.setText(" ");
        CheckDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckDepositActionPerformed(evt);
            }
        });

        jLabel2.setText("For Check Deposit");

        dep1.setText("Enter the Check Amount:");

        jLabel3.setText("ATM");

        WithdrawStatus.setText("Status");

        DepositStatus.setText("Status");

        Message.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Withdrawlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Withdraw, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubmitWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SubmitDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CashDeposit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CheckDeposit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WithdrawStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DepositStatus)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Withdrawlbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CashDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(dep1)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitDeposit)
                    .addComponent(SubmitWithdraw))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WithdrawStatus)
                    .addComponent(DepositStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDepositActionPerformed
        CashDepositActionPerformed(evt);
        CheckDepositActionPerformed(evt);
        //String text = "d";
        //DepositStatus.setText(text);
    }//GEN-LAST:event_SubmitDepositActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawActionPerformed
    String text = Withdraw.getText();
    double d=Double.parseDouble(text);
    ATMWithdraw(d);
    str = getStr();
     }//GEN-LAST:event_WithdrawActionPerformed

    private void CashDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashDepositActionPerformed
    String text = CashDeposit.getText();
    double d=Double.parseDouble(text);  
    setCashDeposit(d);
    text = "Deposit Success The Amount is: "+d;
    DepositStatus.setText(text);
    }//GEN-LAST:event_CashDepositActionPerformed

    private void CheckDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckDepositActionPerformed
    String text = CheckDeposit.getText();
    double d=Double.parseDouble(text);  
    setCheckDeposit(d);
    text = "Deposit Success The Amount is: "+d;
    DepositStatus.setText(text);
    }//GEN-LAST:event_CheckDepositActionPerformed

    private void SubmitWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitWithdrawActionPerformed
        WithdrawActionPerformed(evt);
        String text = str;
        WithdrawStatus.setText(text);
    }//GEN-LAST:event_SubmitWithdrawActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    String text = "Thank You for using Our ATM";
    Message.setText(text);   
    int delay = 2000;
Timer timer = new Timer(2, (ActionListener) this);
timer.setRepeats( false );
timer.start();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CashDeposit;
    private javax.swing.JTextField CheckDeposit;
    private javax.swing.JLabel DepositStatus;
    private javax.swing.JLabel Message;
    private javax.swing.JButton SubmitDeposit;
    private javax.swing.JButton SubmitWithdraw;
    private javax.swing.JTextField Withdraw;
    private javax.swing.JLabel WithdrawStatus;
    private javax.swing.JLabel Withdrawlbl;
    private javax.swing.JLabel dep;
    private javax.swing.JLabel dep1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
